#!/usr/bin/env python3
"""
export_os.py - automated shbt-os release exporter.

Pipeline:
  1. Run the Z3 formal verification (formal/formal_verification.py); abort on failure.
  2. Generate kernel/include/shbt_hal.h from kernel/include/shbt_hardware.h
     (typed register accessors + build provenance).
  3. Locate a freestanding cross-compiler:
        clang -target x86_64-unknown-none   |   x86_64-elf-gcc
     and build the kernel object.  If neither is present, emit a mock ELF64
     relocatable object with a valid ELF header so downstream packaging and
     digest steps still execute (marked `toolchain: mock`).
  4. Package sources, headers, object, formal report and manifest into
     shbt_os_release.zip.
  5. Write SHA-256 digests (SHA256SUMS) for every artefact and for the zip.

Usage:  python3 scripts/export_os.py [--out build/release] [--skip-formal]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import platform
import re
import shutil
import struct
import subprocess
import sys
import time
import zipfile
from dataclasses import dataclass, asdict, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from formal import formal_verification as fv  # noqa: E402

KERNEL_INC = REPO_ROOT / "kernel" / "include"
KERNEL_SRC = REPO_ROOT / "kernel" / "src"
HARDWARE_HEADER = KERNEL_INC / "shbt_hardware.h"
HAL_HEADER = KERNEL_INC / "shbt_hal.h"
RUNTIME_SRC = KERNEL_SRC / "shbt_core_runtime.c"
RELEASE_ZIP_NAME = "shbt_os_release.zip"
RELEASE_VERSION = "0.1.0"


# ---------------------------------------------------------------------------
# Register map parsing
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class RegisterDef:
    name: str          # e.g. "IRQ_CLEAR"
    offset: int


def parse_register_map(header: Path = HARDWARE_HEADER) -> List[RegisterDef]:
    text = header.read_text()
    regs = []
    for m in re.finditer(r"#define\s+SHBT_REG_([A-Z0-9_]+)\s+(0x[0-9A-Fa-f]+)U", text):
        regs.append(RegisterDef(m.group(1), int(m.group(2), 16)))
    if not regs:
        raise RuntimeError(f"no SHBT_REG_* definitions found in {header}")
    return sorted(regs, key=lambda r: r.offset)


def git_revision() -> str:
    try:
        return subprocess.check_output(["git", "rev-parse", "--short=12", "HEAD"], cwd=REPO_ROOT,
                                       stderr=subprocess.DEVNULL, text=True).strip()
    except (OSError, subprocess.CalledProcessError):
        return "unknown"


# ---------------------------------------------------------------------------
# HAL header generation
# ---------------------------------------------------------------------------

def generate_hal_header(out: Path = HAL_HEADER, formal_report: Optional[fv.VerificationReport] = None) -> Path:
    regs = parse_register_map()
    phase_base = next(r.offset for r in regs if r.name == "PHASE_BASE")
    scalar = [r for r in regs if r.name != "PHASE_BASE"]
    rev = git_revision()
    stamp = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
    proved = formal_report.all_passed if formal_report else False
    wc = formal_report.worst_case_recovery_ns if formal_report else 0.0

    L: List[str] = []
    w = L.append
    w("/*")
    w(" * shbt_hal.h - GENERATED by scripts/export_os.py.  DO NOT EDIT.")
    w(f" *   source   : kernel/include/shbt_hardware.h @ {rev}")
    w(f" *   generated: {stamp}")
    w(f" *   formal   : recovery <= {fv.RECOVERY_BOUND_NS_X100/100:.2f} ns {'PROVED' if proved else 'UNVERIFIED'}"
      f" (worst case {wc:.2f} ns)")
    w(" *")
    w(" * Freestanding hardware abstraction layer: typed volatile accessors over the")
    w(" * SHBT-R MMIO aperture.  Depends only on <stdint.h> and shbt_hardware.h.")
    w(" */")
    w("#ifndef SHBT_HAL_H")
    w("#define SHBT_HAL_H")
    w("")
    w("#include <stdint.h>")
    w('#include "shbt_hardware.h"')
    w("")
    w("#ifdef __cplusplus")
    w('extern "C" {')
    w("#endif")
    w("")
    w(f'#define SHBT_HAL_VERSION            "{RELEASE_VERSION}"')
    w(f'#define SHBT_HAL_SOURCE_REVISION    "{rev}"')
    w(f"#define SHBT_HAL_FORMALLY_VERIFIED  {1 if proved else 0}")
    w(f"#define SHBT_HAL_RECOVERY_WCET_NS_X100 {int(round(wc * 100))}U")
    w("")
    w("static inline uint32_t shbt_hal_rd(uintptr_t off)")
    w("{")
    w("    return *(volatile uint32_t *)((uintptr_t)SHBT_MMIO + off);")
    w("}")
    w("")
    w("static inline void shbt_hal_wr(uintptr_t off, uint32_t v)")
    w("{")
    w("    *(volatile uint32_t *)((uintptr_t)SHBT_MMIO + off) = v;")
    w("}")
    w("")
    w("/* ---- scalar registers ------------------------------------------------ */")
    for r in scalar:
        lname = r.name.lower()
        w(f"/* {r.name} @ 0x{r.offset:04X} */")
        w(f"static inline uint32_t shbt_hal_read_{lname}(void) {{ return shbt_hal_rd(SHBT_REG_{r.name}); }}")
        w(f"static inline void     shbt_hal_write_{lname}(uint32_t v) {{ shbt_hal_wr(SHBT_REG_{r.name}, v); }}")
        w(f"static inline void     shbt_hal_set_{lname}(uint32_t m) {{ shbt_hal_wr(SHBT_REG_{r.name}, shbt_hal_rd(SHBT_REG_{r.name}) | m); }}")
        w(f"static inline void     shbt_hal_clear_{lname}(uint32_t m) {{ shbt_hal_wr(SHBT_REG_{r.name}, shbt_hal_rd(SHBT_REG_{r.name}) & ~m); }}")
        w("")
    w("/* ---- phase register array ------------------------------------------- */")
    w(f"#define SHBT_HAL_PHASE_OFFSET(ch)  (0x{phase_base:04X}U + 4U * (uintptr_t)(ch))")
    w("static inline uint32_t shbt_hal_read_phase(uint32_t ch) { return shbt_hal_rd(SHBT_HAL_PHASE_OFFSET(ch)); }")
    w("static inline void     shbt_hal_write_phase(uint32_t ch, uint32_t v) { shbt_hal_wr(SHBT_HAL_PHASE_OFFSET(ch), v); }")
    w("")
    w("/* ---- 64-bit free-running timer (hi/lo/hi read with retry) ------------ */")
    w("static inline uint64_t shbt_hal_read_timer_ns(void)")
    w("{")
    w("    uint32_t hi1, lo, hi2;")
    w("    do {")
    w("        hi1 = shbt_hal_read_timer_hi();")
    w("        lo  = shbt_hal_read_timer_lo();")
    w("        hi2 = shbt_hal_read_timer_hi();")
    w("    } while (hi1 != hi2);")
    w("    return ((uint64_t)hi1 << 32) | lo;")
    w("}")
    w("")
    w("#ifdef __cplusplus")
    w("}")
    w("#endif")
    w("#endif /* SHBT_HAL_H */")
    out.write_text("\n".join(L) + "\n")
    return out


# ---------------------------------------------------------------------------
# Toolchain discovery and build
# ---------------------------------------------------------------------------

@dataclass
class Toolchain:
    kind: str                       # "clang" | "x86_64-elf-gcc" | "mock"
    command: List[str] = field(default_factory=list)
    version: str = ""


def _probe(cmd: List[str]) -> Optional[str]:
    if shutil.which(cmd[0]) is None:
        return None
    try:
        out = subprocess.run(cmd, capture_output=True, text=True, timeout=20)
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    return (out.stdout or out.stderr).splitlines()[0] if (out.stdout or out.stderr) else "ok"


def find_freestanding_toolchain() -> Toolchain:
    """Prefer clang with an explicit bare-metal target, then a dedicated ELF cross-gcc."""
    ver = _probe(["clang", "-target", "x86_64-unknown-none", "--version"])
    if ver:
        return Toolchain("clang", ["clang", "-target", "x86_64-unknown-none"], ver)
    ver = _probe(["x86_64-elf-gcc", "--version"])
    if ver:
        return Toolchain("x86_64-elf-gcc", ["x86_64-elf-gcc"], ver)
    return Toolchain("mock")


COMMON_CFLAGS = ["-std=c11", "-O2", "-ffreestanding", "-nostdlib", "-fno-builtin",
                 "-fno-stack-protector", "-mno-red-zone", "-mavx512f", "-Wall", "-Wextra"]


def build_kernel_object(tc: Toolchain, out_obj: Path) -> Tuple[bool, str]:
    cmd = tc.command + COMMON_CFLAGS + ["-I", str(KERNEL_INC), "-c", str(RUNTIME_SRC), "-o", str(out_obj)]
    res = subprocess.run(cmd, capture_output=True, text=True)
    return res.returncode == 0, (res.stderr or res.stdout).strip()


def write_mock_elf_object(out_obj: Path) -> None:
    """Emit a minimal, structurally valid ELF64 relocatable (ET_REL, x86-64) object.

    Layout: ELF header, a `.note.shbt` payload describing the build, a string
    table, and three section headers (NULL, .note.shbt, .shstrtab).
    """
    note = json.dumps({"mock": True, "reason": "no freestanding toolchain on host",
                       "source": RUNTIME_SRC.name, "revision": git_revision()}).encode()
    note += b"\0" * (-len(note) % 8)
    shstrtab = b"\0.note.shbt\0.shstrtab\0"
    shstrtab += b"\0" * (-len(shstrtab) % 8)

    ehsize, shentsize = 64, 64
    note_off = ehsize
    shstr_off = note_off + len(note)
    shoff = shstr_off + len(shstrtab)

    e_ident = b"\x7fELF" + bytes([2, 1, 1, 0]) + b"\0" * 8      # 64-bit, LE, v1, SysV
    ehdr = e_ident + struct.pack("<HHIQQQIHHHHHH",
                                 1,        # e_type   ET_REL
                                 62,       # e_machine EM_X86_64
                                 1,        # e_version
                                 0,        # e_entry
                                 0,        # e_phoff
                                 shoff,    # e_shoff
                                 0,        # e_flags
                                 ehsize, 0, 0, shentsize, 3, 2)  # ehsize phentsize phnum shentsize shnum shstrndx

    def shdr(name, typ, flags, off, size, align):
        return struct.pack("<IIQQQQIIQQ", name, typ, flags, 0, off, size, 0, 0, align, 0)

    shdrs = shdr(0, 0, 0, 0, 0, 0)                                   # SHT_NULL
    shdrs += shdr(1, 7, 0, note_off, len(note), 8)                    # SHT_NOTE
    shdrs += shdr(12, 3, 0, shstr_off, len(shstrtab), 1)              # SHT_STRTAB
    out_obj.write_bytes(ehdr + note + shstrtab + shdrs)


def validate_elf_header(path: Path) -> Dict[str, object]:
    data = path.read_bytes()
    if len(data) < 64 or data[:4] != b"\x7fELF":
        raise ValueError(f"{path} is not an ELF file")
    e_type, e_machine = struct.unpack_from("<HH", data, 16)
    return {"class": "ELF64" if data[4] == 2 else "ELF32", "type": e_type, "machine": e_machine,
            "size": len(data)}


# ---------------------------------------------------------------------------
# Packaging and digests
# ---------------------------------------------------------------------------

def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


@dataclass
class ReleaseManifest:
    version: str
    revision: str
    generated_utc: str
    host: str
    toolchain: str
    toolchain_version: str
    kernel_object: str
    elf: Dict[str, object]
    formal_all_passed: bool
    formal_worst_case_recovery_ns: float
    formal_recovery_bound_ns: float
    files: Dict[str, str] = field(default_factory=dict)   # relative path -> sha256


@dataclass
class ExportResult:
    out_dir: Path
    zip_path: Path
    zip_sha256: str
    manifest: ReleaseManifest
    formal_report: Optional[fv.VerificationReport]


def export(out_dir: Path, skip_formal: bool = False, verbose: bool = True) -> ExportResult:
    out_dir.mkdir(parents=True, exist_ok=True)
    stage = out_dir / "stage"
    if stage.exists():
        shutil.rmtree(stage)
    (stage / "kernel" / "include").mkdir(parents=True)
    (stage / "kernel" / "src").mkdir(parents=True)
    (stage / "bin").mkdir()
    (stage / "formal").mkdir()

    log = print if verbose else (lambda *a, **k: None)

    # 1. formal verification
    report: Optional[fv.VerificationReport] = None
    if not skip_formal:
        log("[1/5] Z3 formal verification")
        report = fv.verify(verbose=verbose)
        if not report.all_passed:
            raise SystemExit("formal verification FAILED - release aborted")
        (stage / "formal" / "formal_report.json").write_text(report.to_json())
    else:
        log("[1/5] formal verification skipped (--skip-formal)")

    # 2. HAL header
    log("[2/5] generating kernel/include/shbt_hal.h")
    hal = generate_hal_header(HAL_HEADER, report)
    for src in (HARDWARE_HEADER, hal):
        shutil.copy2(src, stage / "kernel" / "include" / src.name)
    shutil.copy2(RUNTIME_SRC, stage / "kernel" / "src" / RUNTIME_SRC.name)

    # 3. toolchain + build
    log("[3/5] locating freestanding toolchain")
    tc = find_freestanding_toolchain()
    obj = stage / "bin" / "shbt_core_runtime.o"
    if tc.kind != "mock":
        ok, msg = build_kernel_object(tc, obj)
        log(f"      {tc.kind}: {tc.version}")
        if not ok:
            log(f"      build failed, falling back to mock ELF:\n{msg}")
            tc = Toolchain("mock", version=f"fallback after {tc.kind} failure")
            write_mock_elf_object(obj)
        elif msg:
            log(f"      compiler diagnostics:\n{msg}")
    else:
        log("      no clang/x86_64-elf-gcc found - emitting mock ELF64 object")
        write_mock_elf_object(obj)
    elf_info = validate_elf_header(obj)

    # 4. manifest + zip
    log("[4/5] packaging shbt_os_release.zip")
    files = {str(p.relative_to(stage)): sha256_file(p) for p in sorted(stage.rglob("*")) if p.is_file()}
    manifest = ReleaseManifest(
        version=RELEASE_VERSION, revision=git_revision(),
        generated_utc=time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        host=f"{platform.system()} {platform.machine()} python{platform.python_version()}",
        toolchain=tc.kind, toolchain_version=tc.version,
        kernel_object=str(obj.relative_to(stage)), elf=elf_info,
        formal_all_passed=bool(report and report.all_passed),
        formal_worst_case_recovery_ns=report.worst_case_recovery_ns if report else 0.0,
        formal_recovery_bound_ns=fv.RECOVERY_BOUND_NS_X100 / 100,
        files=files,
    )
    (stage / "manifest.json").write_text(json.dumps(asdict(manifest), indent=2))
    sums = "".join(f"{h}  {name}\n" for name, h in files.items())
    sums += f"{sha256_file(stage / 'manifest.json')}  manifest.json\n"
    (stage / "SHA256SUMS").write_text(sums)

    zip_path = out_dir / RELEASE_ZIP_NAME
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for p in sorted(stage.rglob("*")):
            if p.is_file():
                zf.write(p, p.relative_to(stage))

    # 5. digests
    log("[5/5] SHA-256 digests")
    zsha = sha256_file(zip_path)
    (out_dir / f"{RELEASE_ZIP_NAME}.sha256").write_text(f"{zsha}  {RELEASE_ZIP_NAME}\n")
    shutil.copy2(stage / "SHA256SUMS", out_dir / "SHA256SUMS")
    log(f"      {zsha}  {zip_path}")
    log(f"Release exported: {zip_path} ({zip_path.stat().st_size} bytes, toolchain={tc.kind})")
    return ExportResult(out_dir, zip_path, zsha, manifest, report)


def verify_release(result: ExportResult) -> None:
    """Re-open the zip and check every recorded digest; used by the test runner."""
    with zipfile.ZipFile(result.zip_path) as zf:
        names = set(zf.namelist())
        for rel, digest in result.manifest.files.items():
            assert rel in names, f"{rel} missing from zip"
            assert hashlib.sha256(zf.read(rel)).hexdigest() == digest, f"digest mismatch for {rel}"
        assert "SHA256SUMS" in names and "manifest.json" in names
        assert "kernel/include/shbt_hal.h" in names
        hdr = zf.read(result.manifest.kernel_object)
        assert hdr[:4] == b"\x7fELF", "kernel object is not ELF"
    assert sha256_file(result.zip_path) == result.zip_sha256


def main(argv: Optional[List[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(REPO_ROOT / "build" / "release"), help="output directory")
    ap.add_argument("--skip-formal", action="store_true", help="skip the Z3 gate (development only)")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args(argv)
    res = export(Path(args.out), skip_formal=args.skip_formal, verbose=not args.quiet)
    verify_release(res)
    return 0


if __name__ == "__main__":
    sys.exit(main())
